### ISSUE TITLE
Update Submission Form

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/extensions-hackathon#28]
FInal fields:

- Extension title *
- Extension description *
- Your Telegram handle (optional?)
- Repository URL *
- < 2 min video showing the extension
- Feedback about the extension system

Design: (maybe we can also add the text on the left with some info)

![photo_2024-08-15_09-48-21](https://github.com/user-attachments/assets/82d089e6-708a-4e98-99fe-d8514613fa57)

**Comment by damianmarti** [comment]
@carletex I can't see the image, can you please check it?

**Comment by damianmarti** [comment]
@carletex is this the image?

![photo_2024-08-15_09-48-21](https://github.com/user-attachments/assets/82d089e6-708a-4e98-99fe-d8514613fa57)

**Comment by carletex** [comment]
Yep, that's the one!

Sorry, it seems it didn't finish uploading :/
