### ISSUE TITLE
Admin voting, tweak design + responsive

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/extensions-hackathon#35]
Now it is a priority :)

Assigning it to Hunter since he is already tackling many improvements on Admin page 🙏

**Comment by carletex** [comment]
Adding some stuff here:

- [ ] Star: create a hover effect on the stars when voting (if you are in star 6 it will be highlighted and also all the previous stars from 1-5)
- [ ] loading state when clearing votes (`Clear` click)
- [ ] Elegible flag
  - [ ] Find a better place for the eligible flag
  - [ ] loading state when setting / clearing the flag
  - [ ] Give some card UI feedback when set (eg. soft green = eligible, soft blue = not set, soft grey? = non eligible)
![image](https://github.com/user-attachments/assets/846468f8-a25d-48cc-ae0e-25c8fe0078ae)

I'll keep updating the list!

cc @ChangoMan

**Comment by carletex** [comment]
List updated!
