### ISSUE TITLE
Set project video mandatory?

### ISSUE THREAD

**Issue by Pabl0cks** [BuidlGuidl/extensions-hackathon#46]
I think it's nice to make them upload a 2 minute video explaining their project (Extension). 

Maybe we should make it mandatory in the form+schema. If not we'd need to tweak the Q/A proposal of #45

**Comment by carletex** [comment]
No hard opinion on this...I see PROS / CONS. I think it depends on where we want to set the bar for a submission.

**Comment by damianmarti** [comment]
I think by making the video mandatory we set the bar a little higher and maybe in this way we avoid receiving bad or incompleted extensions.

**Comment by carletex** [comment]
Ok, let's do it! Assigned it to you @damianmarti !
