### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/extensions-hackathon#9]
Let's discuss on how admin will be able to vote. Some init ideas:

- We have a `builder` table with `roles`. roles = admin => you can vote
- We can give every admin 100 points (or whatever) and they have to spread out the point to all the different projects => sign.
- Not sure if they should see or not the other votes from admin
- Do we need privates notes?
- Maybe we have some flags (requirements are met, no cheating, the extension work, not spam... etc) so we can have some greenlight before voting.

**Comment by damianmarti** [comment]
> Hey @damianmarti
> 
> All of those flags might be overkill for this one, but I could see that feature in the future template.
> 
> For now: how about we create an "eligible flag"?? Well, not sure if it's just a flag because it can have 3 states, right?
> 
> * Elegible
> * Non elegible
> * (pending) The default state, before an admin has evaluated it.
> 
> > json field
> 
> What are the downsides of this? Hard to query them? I guess it's ok for now.
> 
> We could also just do an extra field, but we'd have to create new columns for new flags in the future. NOt sure, up to you!
> 
> > I think it will be useful to have info about who set each flag, maybe we can add an automatic comment with this information for now.
> 
> If we end up using the JSON field, maybe we can save a prop with the address of the admin who set the flag.

@carletex ok, I can start adding only a field for the Eligible status for now, and we can start using the comments to share more information between the voters.

**Comment by carletex** [comment]
Thanks Damu!

Closing this since we already created the issues / PRs
